#MELANI RODRIGUEZ
#Taller De Programacion
#Comision 2'B'

version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: melani
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 9090:9090
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

  prueba_django:
    # Imágen a utilizar:
    image: python:3.9.5
    # Nombre del container:
    container_name: prueba_djangoISDM
    # Comportamiento ante fallos y al iniciar el sistema:
    restart: always
    # Carpetas enlazadas:
    volumes:
      # Source code directory:
      - type: bind
        source: .
        target: /opt/back_end
    # Puertos enlazados:
    ports:
        - "8000:8000"
    # Control de consola:
    stdin_open: true
    tty: true
    
